<?php
/*
 * Field definitions for the Sellbrite Bulk Loader (from the source workbook).
 *
 *   'values' - dropdown option lists (ODS "Valid Values" sheet); entries
 *              starting with two or more dashes are group separators
 *   'schema' - column definitions (label / required / auto / dropdown key)
 *
 * Coin facts come from the GreySheet API via the agent; these values constrain
 * the controlled fields so displays and autofills stay on-vocabulary.
 */
return [
    // Dropdown option lists, extracted from the ODS "Valid Values" sheet.
    'values' => [
        'bullion_shape' => [
            'Bar', 'Round',
        ],
        'certification' => [
            'Uncertified', 'ANACS', 'CAC', 'ICG',
            'NGC', 'NGC & CAC', 'PCGS', 'PCGS & CAC',
            'U.S. Mint', '--- PAPER MONEY ---', 'PCGS Banknote Grading', 'PCGS Currency',
            'PMG', 'Legacy Currency Grading',
        ],
        'circulated_or_uncirculated' => [
            'Circulated', 'Uncirculated',
        ],
        'coin_design' => [
            'Shield-Type Cob', 'Pillars-Type Cob', 'Milled-Pillar Type', 'Milled-Bust Type',
        ],
        'composition' => [
            'Bronze', 'Copper', 'Copper Alloy', 'Copper-Nickel',
            'Copper-Nickel Clad', 'Copper-Plated Zinc', 'Gold', 'Manganese-Brass',
            'Palladium', 'Platinum', 'Silver', 'Silver Alloy',
            'Silver Clad', 'Zinc-Coated Steel', '-- OTHER --', 'Aluminum-Bronze',
            'Bi-Metallic', 'Billon', 'Brass', 'Nickel-Plated Steel',
            'Nickel-Silver', 'Paper', 'Pewter', 'Sterling Silver',
            'Titanium', 'Zinc Copper Aluminum Alloy', '-- MINT & PROOF SETS --', 'Copper-Nickel, Copper-Alloy',
            'Copper-Nickel, Copper-Alloy, Manganese-Brass', 'Copper-Nickel, Copper-Plated Zinc', 'Copper-Nickel, Copper-Plated Zinc, Manganese-Brass', 'Silver-Clad, Copper-Nickel, Copper-Alloy',
            'Silver, Copper-Nickel', 'Silver, Copper-Nickel, Copper-Alloy', 'Silver, Copper-Nickel, Copper-Alloy, Manganese-Brass', 'Silver, Copper-Nickel, Copper-Plated Zinc',
            'Silver, Copper-Nickel, Copper-Plated Zinc, Manganese-Brass',
        ],
        'condition_note' => [
            'Brand New from the Mint', 'Comes in the GSA \'Soft Pack\' labeled as \'circulated\' on the packaging, but grades out as Uncirculated upon inspection.', 'Slab is damaged. Please see photos.', 'The outer sleeve is missing.',
            'The slab has some scratches and scuffs', 'These rolls are assembled from uncirculated coins from original ballistic bags straight from the U.S. Mint. Coins may display bag marks, minor abrasions caused by contact between pieces during the minting process, or while stored and transported inside a mint bag.', 'These sets are assembled from uncirculated coins from original ballistic bags or rolls straight from the U.S. Mint. Coins may display bag marks, minor abrasions caused by contact between pieces during the minting process, or while stored and transported inside a mint bag.', 'These sets are not brand new. Some of the coins may show signs of age such as toning and spots.',
            'These sets are not brand new. The packaging may show signs of wear such as minor folds and scrapes.', 'This coin may display blemishes from storage or incorrect handling, such as toning, milk spots, cloudy fields, contact marks, etc. Please look at the images carefully before bidding.',
        ],
        'country_of_manufacture' => [
            'United States', 'Afghanistan', 'Aland Islands', 'Albania',
            'Algeria', 'American Samoa', 'Andorra', 'Angola',
            'Anguilla', 'Antarctica', 'Antigua And Barbuda', 'Argentina',
            'Armenia', 'Aruba', 'Australia', 'Austria',
            'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
            'Barbados', 'Belarus', 'Belgium', 'Belize',
            'Benin', 'Bermuda', 'Bhutan', 'Bolivia',
            'Bosnia and Herzegovina', 'Botswana', 'Bouvet Island', 'Brazil',
            'British Indian Ocean Territory', 'British Virgin Islands', 'Brunei', 'Bulgaria',
            'Burkina Faso', 'Burma (Myanmar)', 'Burundi', 'Cambodia',
            'Cameroon', 'Canada', 'Canary Islands', 'Cape Verde',
            'Cayman Islands', 'Central African Republic', 'Chad', 'Chile',
            'China', 'Christmas Island', 'Cocos (Keeling) Islands', 'Colombia',
            'Comoros', 'Cook Islands', 'Costa Rica', 'Croatia',
            'Cuba', 'Cyprus', 'Czech Republic', 'Democratic Republic of the Congo',
            'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic',
            'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea',
            'Eritrea', 'Estonia', 'Ethiopia', 'Falkland Islands',
            'Faroe Islands', 'Fiji', 'Finland', 'France',
            'French Guiana', 'French Polynesia', 'French Southern Territories', 'Gabon',
            'Gambia', 'Georgia', 'Germany', 'Ghana',
            'Gibraltar', 'Greece', 'Greenland', 'Grenada',
            'Guadeloupe', 'Guam', 'Guatemala', 'Guernsey',
            'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti',
            'Heard and McDonald Islands', 'Holy See (Vatican City)', 'Honduras', 'Hong Kong',
            'Hungary', 'Iceland', 'India', 'Indonesia',
            'Iran', 'Iraq', 'Ireland', 'Isle of Man',
            'Israel', 'Italy', 'Ivory Coast', 'Jamaica',
            'Japan', 'Jersey', 'Jordan', 'Kazakhstan',
            'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan',
            'Laos', 'Latvia', 'Lebanon', 'Lesotho',
            'Liberia', 'Libya', 'Liechtenstein', 'Lithuania',
            'Luxembourg', 'Macau', 'Macedonia', 'Madagascar',
            'Malawi', 'Malaysia', 'Maldives', 'Mali',
            'Malta', 'Marshall Islands', 'Martinique', 'Mauritania',
            'Mauritius', 'Mayotte', 'Mexico', 'Micronesia',
            'Moldova', 'Monaco', 'Mongolia', 'Montserrat',
            'Morocco', 'Mozambique', 'Namibia', 'Nauru',
            'Nepal', 'Netherlands', 'Netherlands Antilles', 'New Caledonia',
            'New Zealand', 'Nicaragua', 'Niger', 'Nigeria',
            'Niue', 'Norfolk Island', 'North Korea', 'Northern Mariana Islands',
            'Norway', 'Oman', 'Pakistan', 'Palau',
            'Palestinian Territory', 'Panama', 'Papua New Guinea', 'Paraguay',
            'Peru', 'Philippines', 'Pitcairn Islands', 'Poland',
            'Portugal', 'Puerto Rico', 'Qatar', 'Republic of the Congo',
            'Reunion', 'Romania', 'Russia', 'Rwanda',
            'S. Georgia and S. Sandwich Isls.', 'Saint Helena', 'Saint Kitts And Nevis', 'Saint Lucia',
            'Saint Pierre and Miquelon', 'Saint Vincent And The Grenadines', 'Saint-Martin', 'Samoa',
            'San Marino', 'Sao Tome And Principe', 'Saudi Arabia', 'Senegal',
            'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore',
            'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia',
            'South Africa', 'South Korea', 'Spain', 'Sri Lanka',
            'Sudan', 'Suriname', 'Svalbard', 'Swaziland',
            'Sweden', 'Switzerland', 'Syria', 'Taiwan',
            'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste',
            'Togo', 'Tokelau', 'Tonga', 'Trinidad And Tobago',
            'Tunisia', 'Turkey', 'Turkmenistan', 'Turks And Caicos Islands',
            'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates',
            'United Kingdom', 'Uruguay', 'US Minor Outlying Islands', 'US Virgin Islands',
            'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam',
            'Wallis and Futuna', 'Western Sahara', 'Yemen', 'Zaire',
            'Zambia', 'Zimbabwe', 'Unknown',
        ],
        'designation_abbrivation' => [
            '5DP', '5FS', '5PL', '6DP',
            '6FS', '6PL', 'BM', 'BMCA',
            'BN', 'BNC', 'BNM', 'BNP',
            'BNU', 'C', 'CA', 'CAM',
            'CP', 'DC', 'DCAM', 'DCP',
            'DFM', 'DM', 'DME', 'DMPL',
            'DPL', 'EH', 'ER', 'FB',
            'FBL', 'FBP', 'FD', 'FDD',
            'FDP', 'FH', 'FLP', 'FM',
            'FS', 'FSB', 'FT', 'FTC',
            'FTP', 'FTU', 'MA', 'ME',
            'MS', 'P', 'PFM', 'PL',
            'PME', 'Pos. A', 'Pos. B', 'RB',
            'RBC', 'RBP', 'RBU', 'RD',
            'RD CAM', 'RD DCAM', 'RD UCAM', 'RDC',
            'RDP', 'RDU', 'RFD', 'RFY',
            'RY', 'SA', 'SF', 'SP',
            'UC', 'UCAM',
        ],
        'exact_image' => [
            'The images you see are for the exact item you will receive.', 'The images used for this listing are stock photos from our inventory. Your purchase is guaranteed to match the quality of the product shown.', 'Presale Item. The images used for this listing are stock photos and are only a representation of the item you will receive.', 'The images used for this listing are stock photos and are only a representation of the item you will receive.',
            'The images used for this listing are stock photos from the mint.',
        ],
        'fineness' => [
            '0.35', '0.4', '0.5', '0.75',
            '0.8', '0.8292', '0.835', '0.8924',
            '0.9', '0.9167', '0.925', '0.999',
            '0.9995', '0.9999', '9K', '10K',
            '12K', '14K', '18K', '22K',
            '24K',
        ],
        'grade' => [
            'Ungraded', 'Various Grades', '--- UNCERTIED US COINS ---', 'Poor',
            'Fair', 'Fair Details', 'About Good', 'About Good Details',
            'About Good / Good', 'Good', 'Good Details', 'Good / Very Good',
            'Good / Very Good Details', 'Very Good', 'Very Good Details', 'Very Good / Fine',
            'Very Good / Fine Details', 'About Fine', 'About Fine Details', 'Fine',
            'Fine Details', 'Fine / Very Fine', 'Fine / Very Fine Details', 'Very Fine',
            'Very Fine Details', 'Very Fine / Extremely Fine', 'Very Fine / Extremely Fine Details', 'Very Fine or Better',
            'Extremely Fine', 'Extremely Fine Details', 'Extremely Fine / About Uncirculated', 'Extremely Fine / About Uncirculated Details',
            'Extremely Fine or Better', 'About Uncirculated', 'About Uncirculated Details', 'About Uncirculated / Uncirculated',
            'About Uncirculated / Uncirculated Details', 'Choice About Uncirculated', 'Choice About Uncirculated Details', 'Borderline Uncirculated',
            'Borderline Uncirculated Details', 'Uncirculated', 'Uncirculated Details', 'Choice Uncirculated',
            'Very Choice Uncirculated', 'Gem Uncirculated', 'Gem Uncirculated Details', 'Superb Gem Uncirculated',
            'Perfect Uncirculated', 'Proof', 'Proof Details', 'Choice Proof',
            'Very Choice Proof', 'Gem Proof', 'Superb Gem Proof', 'Ultra Cameo Gem Proof',
            'Perfect Proof', 'Nearly Mint State', 'Mint State', 'Brilliant Uncirculated',
            'Specimen', '--- CERTIFIED COINS ---', 'Genuine', 'AG 3',
            'AG 3 Details', 'AG Details', 'AU 50', 'AU 50 Details',
            'AU 53', 'AU 53 Details', 'AU 55', 'AU 55 Details',
            'AU 58', 'AU 58 Details', 'AU 58+', 'AU Details',
            'EF 40', 'EF 40 Details', 'EF 45', 'EF 45 Details',
            'EU 60', 'EU 61', 'EU 62', 'EU 63',
            'EU 64', 'EU 65', 'EU 66', 'EU 67',
            'EU 68', 'EU 69', 'EU 70', 'F 12',
            'F 12 Details', 'F 15', 'F 15 Details', 'F Details',
            'FR 2', 'FR 2 Details', 'G 4', 'G 4 Details',
            'G 6', 'G 6 Details', 'G Details', 'MS 60',
            'MS 60 Details', 'MS 61', 'MS 62', 'MS 62*',
            'MS 62+', 'MS 63', 'MS 63*', 'MS 63+',
            'MS 63+*', 'MS 64', 'MS 64*', 'MS 64+',
            'MS 64+*', 'MS 65', 'MS 65*', 'MS 65+',
            'MS 65+*', 'MS 66', 'MS 66*', 'MS 66+',
            'MS 66+*', 'MS 67', 'MS 67*', 'MS 67+',
            'MS 67+*', 'MS 68', 'MS 68*', 'MS 68+',
            'MS 68+*', 'MS 69', 'MS 69*', 'MS 69+',
            'MS 69+*', 'MS 70', 'MS 70*', 'MS 70+',
            'MS 70+*', 'PF 55', 'PF 55 Details', 'PF 58',
            'PF 58 Details', 'PF 60', 'PF 60 Details', 'PF 61',
            'PF 62', 'PF 63', 'PF 63*', 'PF 64',
            'PF 64*', 'PF 65', 'PF 65*', 'PF 66',
            'PF 66*', 'PF 67', 'PF 67*', 'PF 67+',
            'PF 68', 'PF 68*', 'PF 69', 'PF 69*',
            'PF 70', 'PF 70*', 'PO 1', 'PR 60',
            'PR 60 Details', 'PR 61', 'PR 62', 'PR 63',
            'PR 64', 'PR 65', 'PR 66', 'PR 67',
            'PR 68', 'PR 69', 'PR 70', 'PR Details',
            'RP 60', 'RP 61', 'RP 62', 'RP 63',
            'RP 64', 'RP 65', 'RP 66', 'RP 67',
            'RP 68', 'RP 69', 'RP 70', 'SP 60',
            'SP 61', 'SP 62', 'SP 63', 'SP 64',
            'SP 65', 'SP 66', 'SP 67', 'SP 68',
            'SP 69', 'SP 70', 'VF 20', 'VF 20 Details',
            'VF 25', 'VF 25 Details', 'VF 30', 'VF 30 Details',
            'VF 35', 'VF 35 Details', 'VF Details', 'VG 10',
            'VG 10 Details', 'VG 8', 'VG 8 Details', 'VG Details',
            'XF 40', 'XF 40 Details', 'XF 45', 'XF 45 Details',
            'XF Details', '--- UNCERTIFIED PAPER MONEY ---', 'About Uncirculated / Crisp Uncirculated', 'Crisp Uncirculated',
            'Choice Crisp Uncirculated', '--- CERTIFIED PAPER MONEY ---', '1', '2',
            '3', '3 Details', '4', '4 Details',
            '6', '6 Details', '8', '8 Details',
            '10', '10 Details', '12', '12 Details',
            '15', '15 Details', '20', '20 Details',
            '25', '25 Details', '30', '30 Details',
            '35', '35 Details', '40', '40 Details',
            '45', '45 Details', '50', '50 Details',
            '53', '53 Details', '55', '55 Details',
            '58', '58 Details', '60', '60 Details',
            '61', '62', '63', '64',
            '65', '66', '67', '68',
            '69', '70', '--- ANCIENTS ---', 'Choice Fine',
            'Choice Very Fine', 'Choice Extremely Fine', 'Choice Mint State',
        ],
        'mint_location' => [
            'Carson City', 'Denver', 'New Orleans', 'Philadelphia',
            'Philadelphia, Denver', 'Philadelphia, Denver, San Francisco', 'Philadelphia, Denver, San Francisco, West Point', 'Philadelphia, Denver, West Point',
            'Philadelphia, San Francisco', 'Philadelphia, San Francisco, West Point', 'Philadelphia, West Point', 'San Francisco',
            'San Francisco, West Point', 'West Point',
        ],
        'mint_mark' => [
            'No Mint Mark', 'CC', 'D', 'D/D',
            'D/S', 'Mo', 'O', 'O/CC',
            'O/O', 'O/S', 'P', 'P, D',
            'P, D, S', 'P, D, S, W', 'P, D, W', 'P, S',
            'P, S, W', 'P, W', 'S', 'S, W',
            'S/S', 'W', 'Various Mint Marks',
        ],
        'modified_item' => [
            'No', 'Yes',
        ],
        'paper_money_type' => [
            'Banknotes', 'Bond Certificates', 'Cancelled Currency', 'Collections & Lots',
            'Commemorative Issue', 'Emergency Issue', 'Errors', 'Hawaii Overprint Note',
            'Hologram', 'Military Currency', 'North Africa Note', 'Notgeld',
            'Polymer Notes', 'Replacement Notes', 'Specimens', 'Uncut Sheets',
            'Wartime Occupation',
        ],
        'single_coin_or_set' => [
            'Single Coin', 'Set',
        ],
        'strike_type' => [
            'Business', 'Burnished', 'Enhanced Uncirculated', 'Matte',
            'Proof-Like', 'Satin', 'Specimen', 'Proof',
            'Brilliant Proof', 'Reverse Proof', 'Satin Proof',
        ],
        'style' => [
            'Circulated', 'Uncirculated', 'Mint', 'Cleaned',
            'Damaged', 'Error', 'Proof', 'Classic Commemorative',
            'Modern Commemorative', 'Pattern', 'Over Date', 'Repunched Date',
        ],
    ],
    'schema' => [
        [
            'name' => 'sku',
            'label' => 'SKU',
            'required' => true,
            'auto' => false,
        ],
        [
            'name' => 'category_name',
            'label' => 'Sellbrite Category Name',
            'required' => false,
            'auto' => false,
            'dropdown' => 'category_name',
        ],
        [
            'name' => 'year',
            'label' => 'Year',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'mint_mark',
            'label' => 'Mint Mark',
            'required' => false,
            'auto' => false,
            'dropdown' => 'mint_mark',
        ],
        [
            'name' => 'mint_location',
            'label' => 'Mint Location',
            'required' => false,
            'auto' => false,
            'dropdown' => 'mint_location',
        ],
        [
            'name' => 'coin_type',
            'label' => 'Coin Type',
            'required' => false,
            'auto' => true,
            'dropdown' => 'coin_type',
        ],
        [
            'name' => 'denomination',
            'label' => 'Denomination',
            'required' => false,
            'auto' => true,
            'dropdown' => 'denomination',
        ],
        [
            'name' => 'coin_variety_1',
            'label' => 'Coin Variety 1',
            'required' => false,
            'auto' => false,
            'dropdown' => 'coin_variety',
        ],
        [
            'name' => 'coin_variety_2',
            'label' => 'Coin Variety 2',
            'required' => false,
            'auto' => false,
            'dropdown' => 'coin_variety',
        ],
        [
            'name' => 'grade',
            'label' => 'Grade',
            'required' => false,
            'auto' => false,
            'dropdown' => 'grade',
        ],
        [
            'name' => 'title_suffix',
            'label' => 'Title Suffix',
            'required' => false,
            'auto' => false,
            'dropdown' => 'title_suffix',
        ],
        [
            'name' => 'designation_abbrivation',
            'label' => 'Designation Abbrivation',
            'required' => false,
            'auto' => false,
            'dropdown' => 'designation_abbrivation',
        ],
        [
            'name' => 'paper_money_grade_designation',
            'label' => 'Paper Money Grade Designation',
            'required' => false,
            'auto' => false,
            'dropdown' => 'paper_money_grade_designation',
        ],
        [
            'name' => 'paper_money_type',
            'label' => 'Paper Money Type',
            'required' => false,
            'auto' => false,
            'dropdown' => 'paper_money_type',
        ],
        [
            'name' => 'certification',
            'label' => 'Certification',
            'required' => false,
            'auto' => false,
            'dropdown' => 'certification',
        ],
        [
            'name' => 'certification_number',
            'label' => 'Certification Number',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'circulated_or_uncirculated',
            'label' => 'Circulated or Uncirculated',
            'required' => false,
            'auto' => true,
            'dropdown' => 'circulated_or_uncirculated',
        ],
        [
            'name' => 'strike_type',
            'label' => 'Strike Type',
            'required' => false,
            'auto' => false,
            'dropdown' => 'strike_type',
        ],
        [
            'name' => 'style',
            'label' => 'Style',
            'required' => false,
            'auto' => false,
            'dropdown' => 'style',
        ],
        [
            'name' => 'composition',
            'label' => 'Composition',
            'required' => false,
            'auto' => true,
            'dropdown' => 'composition',
        ],
        [
            'name' => 'fineness',
            'label' => 'Fineness',
            'required' => false,
            'auto' => true,
            'dropdown' => 'fineness',
        ],
        [
            'name' => 'precious_metal_content',
            'label' => 'Precious Metal Content',
            'required' => false,
            'auto' => false,
            'dropdown' => 'precious_metal_content',
        ],
        [
            // Added per Des (July 2026): straight from GreySheet Diameter (mm).
            'name' => 'diameter',
            'label' => 'Diameter',
            'required' => false,
            'auto' => true,
        ],
        [
            // Added per Des (July 2026): GreySheet WeightOunces (troy oz).
            'name' => 'weight',
            'label' => 'Weight',
            'required' => false,
            'auto' => true,
        ],
        [
            'name' => 'single_coin_or_set',
            'label' => 'Single Coin or Set',
            'required' => false,
            'auto' => false,
            'dropdown' => 'single_coin_or_set',
        ],
        [
            'name' => 'set_count',
            'label' => 'Set Count',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'country_of_manufacture',
            'label' => 'Country of Manufacture',
            'required' => false,
            'auto' => true,
            'dropdown' => 'country_of_manufacture',
        ],
        [
            'name' => 'brand',
            'label' => 'Brand Name',
            'required' => false,
            'auto' => true,
            'dropdown' => 'brand',
        ],
        [
            'name' => 'modified_item',
            'label' => 'Modified Item',
            'required' => false,
            'auto' => false,
            'dropdown' => 'modified_item',
        ],
        [
            'name' => 'modification_description',
            'label' => 'Modification Description',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'bullion_shape',
            'label' => 'Bullion Shape',
            'required' => false,
            'auto' => false,
            'dropdown' => 'bullion_shape',
        ],
        [
            'name' => 'price',
            'label' => 'Price',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'cost',
            'label' => 'Cost',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'quantity',
            'label' => 'Quantity',
            'required' => true,
            'auto' => false,
        ],
        [
            'name' => 'exact_image',
            'label' => 'Exact Image',
            'required' => false,
            'auto' => false,
            'dropdown' => 'exact_image',
        ],
        [
            'name' => 'name',
            'label' => 'Product Name',
            'required' => false,
            'auto' => true,
        ],
        [
            'name' => 'description',
            'label' => 'Product Description',
            'required' => false,
            'auto' => true,
        ],
        [
            'name' => 'red_book_description',
            'label' => 'Red Book Description',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'feature_1',
            'label' => 'Feature 1',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'feature_2',
            'label' => 'Feature 2',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'feature_3',
            'label' => 'Feature 3',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'feature_4',
            'label' => 'Feature 4',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'feature_5',
            'label' => 'Feature 5',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'search_terms',
            'label' => 'Search Terms',
            'required' => false,
            'auto' => true,
        ],
        [
            'name' => 'product_image_1',
            'label' => 'Product Image URL 1',
            'required' => false,
            'auto' => true,
        ],
        [
            'name' => 'product_image_2',
            'label' => 'Product Image URL 2',
            'required' => false,
            'auto' => true,
        ],
        [
            'name' => 'product_image_3',
            'label' => 'Product Image URL 3',
            'required' => false,
            'auto' => true,
        ],
        [
            'name' => 'product_image_4',
            'label' => 'Product Image URL 4',
            'required' => false,
            'auto' => true,
        ],
        [
            'name' => 'product_image_5',
            'label' => 'Product Image URL 5',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'product_image_6',
            'label' => 'Product Image URL 6',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'product_image_7',
            'label' => 'Product Image URL 7',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'product_image_8',
            'label' => 'Product Image URL 8',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'creation_date',
            'label' => 'Creation Date',
            'required' => false,
            'auto' => true,
        ],
        [
            'name' => 'package_length',
            'label' => 'Package Length (inches)',
            'required' => false,
            'auto' => true,
        ],
        [
            'name' => 'package_width',
            'label' => 'Package Width (inches)',
            'required' => false,
            'auto' => true,
        ],
        [
            'name' => 'package_height',
            'label' => 'Package Height (inches)',
            'required' => false,
            'auto' => true,
        ],
        [
            'name' => 'package_weight',
            'label' => 'Package Weight (pounds)',
            'required' => false,
            'auto' => true,
        ],
        [
            'name' => 'condition_note',
            'label' => 'Condition Note',
            'required' => false,
            'auto' => false,
            'dropdown' => 'condition_note',
        ],
        [
            'name' => 'upc',
            'label' => 'UPC',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'original_retail',
            'label' => 'Original Retail',
            'required' => false,
            'auto' => true,
        ],
        [
            'name' => 'total_precious_metal_content',
            'label' => 'Total Precious Metal Content',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'paper_money_series_designation',
            'label' => 'Paper Money Series Designation',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'coin_design',
            'label' => 'Coin Design',
            'required' => false,
            'auto' => false,
            'dropdown' => 'coin_design',
        ],
        [
            'name' => 'nativity_item_type',
            'label' => 'Nativity Item Type',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'watch_band_material',
            'label' => 'Watch Band Material',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'watch_band_type',
            'label' => 'Watch Band Type',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'watch_band_width',
            'label' => 'Watch Band Width',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'watch_case_material',
            'label' => 'Watch Case Material',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'watch_case_size',
            'label' => 'Watch Case Size',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'watch_department',
            'label' => 'Watch Department',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'watch_display_type',
            'label' => 'Watch Display Type',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'watch_manufacturer_warranty',
            'label' => 'Watch Manufacturer Warranty',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'watch_movement_type',
            'label' => 'Watch Movement Type',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'watch_water_resistance',
            'label' => 'Watch Water Resistance',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'stamp_color',
            'label' => 'Stamp Color',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'stamp_quality',
            'label' => 'Stamp Quality',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'stamp_type',
            'label' => 'Stamp Type',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'advent_calendar_type',
            'label' => 'Advent Calendar Type',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'advent_calendar_occasion',
            'label' => 'Advent Calendar Occasion',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'advent_calendar_material',
            'label' => 'Advent Calendar Material',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'advent_calendar_number_of_items',
            'label' => 'Advent Calendar Number of Items',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'advent_calendar_shape',
            'label' => 'Advent Calendar Shape',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'advent_calendar_theme',
            'label' => 'Advent Calendar Theme',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'advent_calendar_item_height',
            'label' => 'Advent Calendar Item Height',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'advent_calendar_item_length',
            'label' => 'Advent Calendar Item Length',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'advent_calendar_item_width',
            'label' => 'Advent Calendar Item Width',
            'required' => false,
            'auto' => false,
        ],
        [
            'name' => 'advent_calendar_item_weight',
            'label' => 'Advent Calendar Item Weight',
            'required' => false,
            'auto' => false,
        ],
    ],
];
