<?php
/*    ***************************************************  -->
<!--  * Program Name - SellbriteBulkLoader_dsp.php      *  -->
<!--  *                                                 *  -->
<!--  * Author    - G CHAU                              *  -->
<!--  *             Littleton Coin Company              *  -->
<!--  *             Littleton NH                        *  -->
<!--  ***************************************************   */
?>

<?php
function dspBulkLoader(&$screenData)
{
    require_once __DIR__ . '/SellbriteBulkLoader_logic.php';
    $skus      = $screenData['skus'] ?? [];
    $byName    = Schema::byName();
    $groups    = Schema::groups();
    $textareas = ['description','extended_description','feature_1','feature_2','feature_3',
                  'feature_4','feature_5','condition_note','search_terms'];

    // One form control.
    $renderField = function (array $col) use ($textareas): string {
        $name = $col['name']; $auto = !empty($col['auto']); $req = !empty($col['required']);
        $opts = Schema::optionsFor($col);
        $cls = 'field' . ($auto ? ' is-auto' : '');
        $h  = '<div class="' . $cls . '" data-field="' . sbl_e($name) . '">';
        $h .= '<label for="f_' . sbl_e($name) . '">' . sbl_e($col['label']);
        if ($req)  { $h .= ' <span class="req">*</span>'; }
        if ($auto) { $h .= ' <span class="badge auto" title="Auto-generated by formula. You can override it.">auto</span>'; }
        $h .= '</label>';
        $da = ' data-name="' . sbl_e($name) . '"' . ($auto ? ' data-auto="1"' : '') . ($req ? ' data-required="1"' : '');
        if ($opts) {
            $h .= '<select id="f_' . sbl_e($name) . '" name="' . sbl_e($name) . '"' . $da . '><option value="">&mdash; select &mdash;</option>';
            foreach ($opts as $o) {
                if (preg_match('/^-{2,}/', $o)) { $h .= '<option disabled>' . sbl_e($o) . '</option>'; continue; }
                $h .= '<option value="' . sbl_e($o) . '">' . sbl_e($o) . '</option>';
            }
            $h .= '</select>';
        } elseif (in_array($name, $textareas, true)) {
            $h .= '<textarea id="f_' . sbl_e($name) . '" name="' . sbl_e($name) . '" rows="2"' . $da . '></textarea>';
        } else {
            $h .= '<input type="text" id="f_' . sbl_e($name) . '" name="' . sbl_e($name) . '" value=""' . $da . '>';
        }
        $h .= '<span class="field-msg"></span></div>';
        return $h;
    };
    ?>
<style>
/* ----- green work area + components (shell header/footer come from LCC) ----- */
#stdPage { background:#CCFFCC; padding:18px 26px 28px; font-family:Arial,Helvetica,sans-serif; color:#222; }
#stdPage h1 { font-size:1.3rem; letter-spacing:1px; font-weight:700; color:#1C4532; text-align:center; margin:0 0 14px; }
.sbl-tools { display:flex; align-items:center; gap:10px; flex-wrap:wrap; padding-bottom:14px; margin-bottom:16px; border-bottom:1px solid #a9e2a9; }
.sbl-tools .spacer { flex:1; }
.sbl-search { padding:9px 16px; border-radius:50px; border:2px solid #ccc; font-size:13px; box-shadow:0 4px 8px rgba(0,0,0,.1); outline:none; width:280px; }
.sbl-search:focus { border-color:#007bff; }
.gs-cascade { display:inline-flex; align-items:center; gap:6px; flex-wrap:wrap; }
.gs-cascade input:disabled, .gs-cascade select:disabled { opacity:.5; }
.gs-dd { padding:9px 12px; border-radius:50px; border:2px solid #ccc; font-size:13px; background:#fff; box-shadow:0 4px 8px rgba(0,0,0,.1); outline:none; max-width:170px; }
.gs-dd:focus { border-color:#007bff; }
.mkt-pick { font-size:12px; font-weight:700; color:#1C4532; display:inline-flex; align-items:center; gap:6px; }
.mkt-pick .gs-dd { max-width:120px; }
.ui-autocomplete { max-height:340px; overflow-y:auto; overflow-x:hidden; z-index:9999; font-size:13px; }
.ui-autocomplete .ui-menu-item-wrapper { padding:6px 10px; }
.ui-autocomplete .gs-path { color:#5f6b62; font-size:11px; }
.req-note { font-weight:400; font-size:11px; color:#b3261e; }
.card.apilog ul { list-style:none; margin:0; padding:0; font-size:11.5px; }
.card.apilog li { padding:6px 0; border-bottom:1px solid #eef1ee; line-height:1.4; }
.card.apilog .ep { font-family:Menlo,Consolas,monospace; color:#0056b3; word-break:break-all; }
.card.apilog .got { color:#33413a; }
.card.apilog .ms { color:#8a948d; }
.gs-total { font-weight:400; font-size:11px; color:#0056b3; }
.gs-rawbox summary { cursor:pointer; font-weight:700; color:#1C4532; font-size:13px; }
.gs-rawbox pre { max-height:360px; overflow:auto; background:#f6f8f6; border:1px solid #e0e6e0; border-radius:6px; padding:8px; font-size:11px; line-height:1.4; white-space:pre; margin:8px 0 0; }
.btn { display:inline-flex; align-items:center; gap:6px; padding:9px 20px; border:none; background:#007bff; color:#fff; font-size:14px; font-weight:700; border-radius:50px; cursor:pointer; }
.btn:hover { background:#0056b3; }
.btn.btn-danger { background:#c0392b; } .btn.btn-danger:hover { background:#a33025; }
.btn-ghost { background:#fff; color:#222; border:1px solid #b4b4b4; }
.btn-ghost:hover { color:#007bff; border-color:#007bff; }
.btn-green { background:#2e8b57; } .btn-green:hover { background:#1e6e43; }
.btn-grey { background:#777; } .btn-grey:hover { background:#555; }
/* table */
.table-card { background:#fff; border:1px solid #b4b4b4; border-radius:8px; overflow:hidden; }
table.grid { width:100%; border-collapse:collapse; font-size:13.5px; background:#fff; }
.grid thead th { text-align:left; padding:11px 14px; font-size:12px; color:#fff; background:#007bff; }
.grid td { padding:10px 14px; border-bottom:1px solid #e4e4e4; }
.grid tbody tr:nth-child(even){ background:#f8f8f8; } .grid tbody tr:hover{ background:#eaf3ff; }
.grid .num { text-align:right; } .sku-link { font-family:Consolas,monospace; color:#007bff; font-weight:700; cursor:pointer; }
.sku-link:hover{ text-decoration:underline; }
.mini { font-size:12px; color:#555; padding:4px 12px; border-radius:50px; border:1px solid #b4b4b4; background:#fff; cursor:pointer; font-weight:700; }
.mini:hover{ color:#007bff; border-color:#007bff; } .mini.danger:hover{ color:#fff; background:#cd0a0a; border-color:#cd0a0a; }
.empty { text-align:center; padding:40px; color:#5f6b62; }
/* form */
.editor { display:grid; grid-template-columns:1fr 300px; gap:20px; align-items:start; margin-top:6px; }
.form-col { display:flex; flex-direction:column; gap:14px; }
.card { background:#fff; border:1px solid #b4b4b4; border-radius:8px; padding:16px; }
fieldset.group, details.group { border:1px solid #b4b4b4; border-radius:8px; }
details.group { padding:12px 14px; margin-bottom:14px; background:#fff; }
.group legend, .group summary { font-size:12.5px; font-weight:700; text-transform:uppercase; color:#1C4532; padding:0 6px; }
details.group summary { cursor:pointer; color:#1e6e43; list-style:none; user-select:none; }
details.group summary::before { content:'\25B8'; display:inline-block; margin-right:6px; transition:transform .15s; }
details.group[open] summary::before { transform:rotate(90deg); }
details.group summary::-webkit-details-marker { display:none; }
.field-grid { display:grid; grid-template-columns:1fr 1fr; gap:12px 16px; margin-top:10px; }
.field { display:flex; flex-direction:column; gap:4px; }
.field label { font-size:12px; color:#5f6b62; font-weight:700; display:flex; gap:6px; align-items:center; }
.field .req { color:#cd0a0a; }
.field input,.field select,.field textarea { background:#f8f8f8; border:1px solid #b4b4b4; border-radius:4px; padding:8px 10px; font-size:13px; font-family:inherit; width:100%; }
.field input:focus,.field select:focus,.field textarea:focus { outline:none; border-color:#007bff; background:#fff; box-shadow:0 0 0 3px rgba(0,123,255,.15); }
/* Auto-filled inputs stay the normal grey box - only the blue AUTO badge on
   the label marks them. Required fields go red via .is-error when empty. */
.badge.auto,.badge.gsauto { font-size:9.5px; text-transform:uppercase; font-weight:700; padding:2px 7px; border-radius:50px; background:#d6e9ff; color:#0056b3; }
.field-msg { font-size:11px; min-height:13px; color:#5f6b62; }
.field.is-error input,.field.is-error select,.field.is-error textarea { border-color:#cd0a0a; background:#fff6f5; } .field.is-error .field-msg { color:#cd0a0a; }
.field.is-action input,.field.is-action select,.field.is-action textarea { border-color:#e0a800; background:#fffaf0; } .field.is-action .field-msg { color:#9a6a14; }
.field[data-field="name"],.field[data-field="description"],.field[data-field="search_terms"],.field[data-field="extended_description"],.field[data-field="condition_note"] { grid-column:1 / -1; }
.preview-col { display:flex; flex-direction:column; gap:14px; }
.preview h3,.checklist h3 { margin:0 0 10px; font-size:12px; text-transform:uppercase; color:#1C4532; }
.preview-img { aspect-ratio:1/1; border-radius:6px; overflow:hidden; background:#f8f8f8; display:grid; place-items:center; margin-bottom:10px; border:1px solid #b4b4b4; position:relative; }
.preview-img img { width:100%; height:100%; object-fit:cover; } .preview-img img.broken { display:none; }
.img-fallback { position:absolute; color:#5f6b62; font-size:13px; } .preview-img img:not(.broken)+.img-fallback { display:none; }
.pv-title { font-weight:700; font-size:14px; margin-bottom:6px; } .pv-price { color:#1e6e43; font-weight:800; font-size:16px; }
.pv-qty { color:#5f6b62; font-size:12px; font-weight:700; margin-left:8px; }
.pv-desc { color:#5f6b62; font-size:12px; line-height:1.5; margin:8px 0 0; max-height:150px; overflow:auto; }
.checklist ul { list-style:none; margin:0; padding:0; display:flex; flex-direction:column; gap:6px; }
.checklist li { font-size:12px; } .checklist li.err{ color:#cd0a0a; } .checklist li.action{ color:#9a6a14; } .checklist li.ok{ color:#1d7a37; }
.pill { padding:6px 14px; border-radius:50px; font-size:12px; font-weight:700; }
.pill.ok { background:#fbf9ee; border:1px solid #fcefa1; color:#2d6a2d; } .pill.err { background:#fef1ec; border:1px solid #cd0a0a; color:#cd0a0a; }
#sbl-spinner { position:fixed; inset:0; background:rgba(255,255,255,.6); z-index:9999; display:none; }
#sbl-spinner.progress { display:block; }
#sbl-spinner .ld { position:absolute; top:42%; left:50%; transform:translateX(-50%); border:6px solid #f3f3f3; border-top:6px solid #007bff; border-radius:50%; width:44px; height:44px; animation:sblspin 1s linear infinite; }
@keyframes sblspin { to { transform:translateX(-50%) rotate(360deg); } }
@media (max-width:980px){ .editor{ grid-template-columns:1fr; } .field-grid{ grid-template-columns:1fr; } }
</style>

<div id="sbl-spinner"><div class="ld"></div></div>

<div id='stdPage'>
    <h1>Sellbrite Bulk Loader</h1>

    <div id="errorMsg" class="ui-state-error ui-corner-all ui-helper-hidden" style="display:none"></div>
    <div id="successMsg" class="ui-state-highlight ui-corner-all ui-helper-hidden" style="display:none"></div>

    <!-- ============ INVENTORY VIEW ============ -->
    <div id="listView">
        <div class="sbl-tools">
            <input type="search" id="sbl-search" class="sbl-search" placeholder="Search SKU, category or title&hellip;"
                   onkeyup="if(event.key==='Enter'){sblSearch();}">
            <button type="button" class="btn btn-ghost" onclick="sblSearch()">Search</button>
            <span class="spacer"></span>
            <select id="new-market" class="gs-dd" title="Marketplace this SKU is being made for - its market fields autofill and appear on the form">
                <option value="">All markets</option>
                <option value="amazon">Amazon</option>
                <option value="ebay">eBay</option>
                <option value="walmart">Walmart</option>
            </select>
            <button type="button" class="btn" onclick="sblNew()">+ New SKU</button>
            <button type="button" class="btn btn-green" onclick="sblExport()" title="Sellbrite product CSV">Export CSV</button>
            <button type="button" class="btn btn-danger" onclick="sblDeleteAll()" title="Permanently delete every SKU">Delete All</button>
        </div>

        <div id="list-empty" class="empty"<?= $skus ? ' style="display:none"' : '' ?>>No SKUs yet. Click <strong>+ New SKU</strong> to add the first one.</div>
        <div id="list-table" class="table-card"<?= $skus ? '' : ' style="display:none"' ?>>
        <table class="grid">
            <thead><tr><th>Market</th><th>SKU</th><th>Category</th><th>Title</th><th>Grade</th>
                <th class="num">Price</th><th class="num">Qty</th><th>Updated</th><th></th></tr></thead>
            <tbody id="sku-tbody">
            <?php foreach ($skus as $r): ?>
                <tr id="sku-row-<?= (int) $r['id'] ?>">
                    <td><?= sbl_e(ucfirst((string) ($r['marketplace'] ?? ''))) ?: 'All' ?></td>
                    <td><span class="sku-link" onclick="sblEdit(<?= (int) $r['id'] ?>)"><?= sbl_e($r['sku']) ?></span></td>
                    <td><?= sbl_e($r['category_name'] ?? '') ?></td>
                    <td><?= sbl_e($r['name'] ?? '') ?></td>
                    <td><?= sbl_e($r['grade'] ?? '') ?></td>
                    <td class="num"><?= ($r['price'] ?? '') !== '' ? '$' . sbl_e($r['price']) : '&mdash;' ?></td>
                    <td class="num"><?= sbl_e($r['quantity'] ?? '') ?: '&mdash;' ?></td>
                    <td><?= sbl_e($r['updated_at'] ?? '') ?></td>
                    <td style="text-align:right">
                        <button type="button" class="mini" onclick="sblEdit(<?= (int) $r['id'] ?>)">Edit</button>
                        <button type="button" class="mini danger" onclick="sblDelete(<?= (int) $r['id'] ?>,'<?= sbl_e($r['sku']) ?>')">Delete</button>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        </div>
    </div>

    <!-- ============ ADD / EDIT VIEW ============ -->
    <div id="formView" style="display:none">
        <div class="sbl-tools">
            <button type="button" class="btn btn-grey" onclick="sblBackToList()">&larr; Inventory</button>
            <span id="formTitle" style="font-weight:700;color:#1C4532;"></span>
            <label class="mkt-pick" title="Marketplace for this SKU">Market
                <select id="f_marketplace" name="marketplace" data-name="marketplace" class="gs-dd" onchange="sblMarketApply()">
                    <option value="">All</option>
                    <option value="amazon">Amazon</option>
                    <option value="ebay">eBay</option>
                    <option value="walmart">Walmart</option>
                </select>
            </label>
            <span class="spacer"></span>
            <span class="gs-cascade" title="Tree &rarr; series &rarr; year &rarr; coin, then Autofill">
                <select id="gs-root" class="gs-dd"><option value="">1. Tree&hellip;</option></select>
                <input type="text" id="gs-series" class="sbl-search" style="width:180px" autocomplete="off"
                       placeholder="2. Series (Morgan Dollars)&hellip;" disabled>
                <select id="gs-year" class="gs-dd" disabled><option value="">Year</option></select>
                <input type="text" id="gs-coin" class="sbl-search" style="width:180px" autocomplete="off"
                       placeholder="4. Coin&hellip;" disabled>
                <button type="button" class="btn" id="gs-autofill" onclick="sblGsAutofill()" disabled
                        title="Fill the highlighted fields from GreySheet">Autofill</button>
            </span>
            <span id="valid-pill" class="pill ok">Ready</span>
            <button type="button" class="btn" id="save-btn" onclick="sblSave()">Save SKU</button>
        </div>

        <div class="editor">
            <form id="sku-form" autocomplete="off" onsubmit="return false;">
                <input type="hidden" name="id" id="f_id" value="">
                <?php
                // Collapsible sections keep the big form uncluttered. Required
                // fields (Sellbrite "mandatory for all") come from the schema;
                // most auto-fill, so requiring them just flags what a listing needs.
                $required = array_merge(Schema::requiredNames(), ['quantity', 'cost']);
                $required = array_values(array_unique($required));
                $sections = [
                    'Coin details' => ['open' => true, 'fields' => [
                        'sku','category_name','coin_type','year','mint_mark','mint_location',
                        'denomination','coin_variety_1','coin_variety_2','grade',
                        'designation_abbrivation','strike_type','circulated_or_uncirculated',
                        'composition','fineness','diameter','weight',
                        'precious_metal_content','total_precious_metal_content',
                        'single_coin_or_set','set_count','country_of_manufacture','brand','title_suffix',
                        'condition','bullion_shape','coin_design',
                        'paper_money_grade_designation','paper_money_type','paper_money_series_designation',
                        'package_weight','exact_image','price','cost','quantity']],
                    'Marketplace fields' => ['open' => false, 'fields' => [
                        'ebay_coin_condition_type','ebay_graded_coin_letter_grade',
                        'ebay_graded_coin_numerical_grade','ebay_graded_coin_professional_grader',
                        'z_ebay_ungraded_coin_condition']],
                    'Other product types (advent calendar / watch / stamp / nativity)' => [
                        'open' => false, 'id' => 'other-products-sec', 'fields' => [
                        'advent_calendar_type','advent_calendar_occasion','advent_calendar_material',
                        'advent_calendar_number_of_items','advent_calendar_shape','advent_calendar_theme',
                        'advent_calendar_item_height','advent_calendar_item_length',
                        'advent_calendar_item_width','advent_calendar_item_weight',
                        'watch_band_material','watch_band_type','watch_band_width','watch_case_material',
                        'watch_case_size','watch_department','watch_display_type',
                        'watch_manufacturer_warranty','watch_movement_type','watch_water_resistance',
                        'stamp_color','stamp_quality','stamp_type','nativity_item_type']],
                    'Listing content' => ['open' => false, 'fields' => [
                        'name','description','extended_description',
                        'feature_1','feature_2','feature_3','feature_4','feature_5','search_terms']],
                    'Product images' => ['open' => false, 'images' => true, 'fields' => [
                        'product_image_1','product_image_2','product_image_3','product_image_4',
                        'product_image_5','product_image_6','product_image_7','product_image_8']],
                ];
                foreach ($sections as $title => $sec) {
                    echo '<details class="card group"' . (!empty($sec['open']) ? ' open' : '')
                       . (!empty($sec['id']) ? ' id="' . sbl_e($sec['id']) . '"' : '') . '>';
                    echo '<summary>' . sbl_e($title) . '</summary><div class="field-grid">';
                    $manual = !empty($sec['id']) && $sec['id'] === 'other-products-sec';   // GreySheet has nothing for these
                    // Computed fields keep updating live even though they are
                    // required (Product Name, Description, the derived copy...).
                    $autoAlways = ['name','description','extended_description',
                                   'feature_1','feature_2','feature_3','feature_4','feature_5',
                                   'search_terms','creation_date','condition','exact_image',
                                   'country_of_manufacture','brand'];
                    foreach ($sec['fields'] as $n) {
                        if (!isset($byName[$n])) { continue; }
                        $col = $byName[$n];
                        $col['required'] = in_array($n, $required, true);
                        // Product images are manual (operator pastes real photo URLs);
                        // other sections are auto unless required-and-operator-owned.
                        $col['auto'] = !empty($sec['images']) ? false
                            : (!$manual && (!$col['required'] || in_array($n, $autoAlways, true)));
                        echo $renderField($col);
                    }
                    echo '</div></details>';
                }
                ?>
            </form>

            <aside class="preview-col">
                <div class="card preview"><h3>Listing preview</h3>
                    <div class="preview-img"><img id="pv-img" src="" alt="" onerror="this.classList.add('broken')">
                        <span class="img-fallback">&#9673; image preview</span></div>
                    <div class="pv-title" id="pv-title">Product title appears here</div>
                    <div><span class="pv-price" id="pv-price"></span><span class="pv-qty" id="pv-qty"></span></div>
                    <p class="pv-desc" id="pv-desc"></p>
                </div>
                <div class="card checklist"><h3>Validation</h3>
                    <ul id="issue-list"><li style="color:#5f6b62">Live as you type&hellip;</li></ul></div>
                <div class="card apilog"><h3>API calls <span id="gs-total" class="gs-total"><?php
                    $__calls = (int) ($_SESSION['gs_api_calls'] ?? 0);
                    if ($__calls > 0) { echo '&middot; ' . number_format($__calls) . ' used this session'; }
                ?></span></h3>
                    <ul id="gs-apilog"><li style="color:#5f6b62">Autofill a coin to see the GreySheet calls&hellip;</li></ul></div>
                <details class="card apilog gs-rawbox"><summary>Raw GreySheet data</summary>
                    <pre id="gs-raw">Autofill a coin to see the full API response&hellip;</pre></details>
            </aside>
        </div>
    </div>
</div>
<?php
}
